#!/usr/bin/env ts-node
// Generates programs/shielded_pool_anchor/src/zk_vk_withdraw_sol_v1.rs from a
// snarkjs verification_key.json that lives outside the repository.
//
// Usage:
//   npx ts-node --project tsconfig.json scripts/generate_rust_vk.ts \
//     <vk-path> <expected-sha256> <output-rs-path>
//
// The script:
//   1. Reads and SHA-256-hashes the input VK JSON file.
//   2. Fails hard if the hash does not match <expected-sha256>.
//   3. Encodes the VK using lib/zk_prover/vk_parser.ts.
//   4. Writes a self-contained .rs file with the VK bytes embedded.
//
// The raw verification_key.json is never copied into the repository.

import * as fs from "fs";
import * as crypto from "crypto";
import * as path from "path";
import { loadAndEncodeSnarkjsGroth16VerificationKey } from "../lib/zk_prover/vk_parser";

// ── CLI args ──────────────────────────────────────────────────────────────────

const [, , vkPath, expectedSha256, outputPath] = process.argv;

if (!vkPath || !expectedSha256 || !outputPath) {
  process.stderr.write(
    "Usage: generate_rust_vk.ts <vk-path> <expected-sha256> <output-rs-path>\n"
  );
  process.exit(1);
}

// ── SHA-256 verification ──────────────────────────────────────────────────────

let vkRaw: Buffer;
try {
  vkRaw = fs.readFileSync(vkPath);
} catch (e: unknown) {
  const msg = e instanceof Error ? e.message : String(e);
  process.stderr.write(`ERROR: cannot read VK file ${vkPath}: ${msg}\n`);
  process.exit(1);
}

const actualSha256 = crypto.createHash("sha256").update(vkRaw).digest("hex");

if (actualSha256 !== expectedSha256.toLowerCase()) {
  process.stderr.write(
    `ERROR: VK hash mismatch\n` +
      `  expected: ${expectedSha256.toLowerCase()}\n` +
      `  actual:   ${actualSha256}\n`
  );
  process.exit(1);
}

process.stdout.write(`VK_HASH_MATCH: ${actualSha256}\n`);

// ── Encode VK ─────────────────────────────────────────────────────────────────

const vk = loadAndEncodeSnarkjsGroth16VerificationKey(vkPath);

if (vk.nrPubinputs !== 4) {
  process.stderr.write(
    `ERROR: expected nrPubinputs=4, got ${vk.nrPubinputs}\n`
  );
  process.exit(1);
}
if (vk.vkIc.length !== 4) {
  process.stderr.write(
    `ERROR: expected vkIc.length=4, got ${vk.vkIc.length}\n`
  );
  process.exit(1);
}

// ── Rust byte literal helpers ─────────────────────────────────────────────────

function fmtBytes(bytes: number[], indent: string): string {
  // Format as a multi-line Rust byte array literal with 16 bytes per line.
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.slice(i, i + 16);
    lines.push(indent + "    " + chunk.map((b) => String(b)).join(", ") + ",");
  }
  return lines.join("\n");
}

function rustArrayLiteral(bytes: number[], indent: string): string {
  return `[\n${fmtBytes(bytes, indent)}\n${indent}]`;
}

// ── Build Rust source ─────────────────────────────────────────────────────────

const icEntries = vk.vkIc
  .map(
    (ic, i) =>
      `    // IC[${i}]${
        i === 0
          ? ": constant term"
          : i === 1
          ? ": root"
          : i === 2
          ? ": nullifier_hash"
          : ": tx_hash"
      }\n` + `    ${rustArrayLiteral(ic, "    ")},`
  )
  .join("\n");

const rs = `// AUTO-GENERATED by scripts/generate_rust_vk.ts.
//
// Source: verification_key.json (not committed; lives outside the repo).
// VK sha256: ${actualSha256}
// Must match artifact_manifest.json verification_key_hash_sha256.
//
// Deployment scope: devnet-only.
// Audit status:     not-audited.
// Do not use on mainnet or in any environment where real funds are at risk.
//
// Field name note: vk_gamme_g2 (two m's) is an intentional typo present in the
// groth16-solana 0.2.0 crate. It must be spelled exactly this way.
//
// VK bytes were generated from the verified WITHDRAW_SOL_V1 verification_key.json.
// Do not manually edit these values. Regenerate this file from a new verified VK
// if the circuit, setup, or artifact manifest changes.
// nr_pubinputs = 4 = IC.length = nPublic(3) + constant_term(1).
//
// VK rotation requires a program upgrade (binary-embedded; no VkRegistry PDA yet).
// Do not reuse this constant for other circuits.
// Re-run this script against a new verification_key.json to rotate the VK.

use groth16_solana::groth16::Groth16Verifyingkey;

static WITHDRAW_SOL_V1_VK_IC: [[u8; 64]; 4] = [
${icEntries}
];

pub(crate) static WITHDRAW_SOL_V1_VK: Groth16Verifyingkey<'static> = Groth16Verifyingkey {
    nr_pubinputs: ${vk.nrPubinputs},
    vk_alpha_g1: ${rustArrayLiteral(vk.vkAlphaG1, "")},
    vk_beta_g2: ${rustArrayLiteral(vk.vkBetaG2, "")},
    vk_gamme_g2: ${rustArrayLiteral(vk.vkGammeG2, "")},
    vk_delta_g2: ${rustArrayLiteral(vk.vkDeltaG2, "")},
    vk_ic: &WITHDRAW_SOL_V1_VK_IC,
};
`;

// ── Write output ──────────────────────────────────────────────────────────────

const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  process.stderr.write(
    `ERROR: output directory does not exist: ${outputDir}\n`
  );
  process.exit(1);
}

fs.writeFileSync(outputPath, rs, "utf8");
process.stdout.write(`WRITTEN: ${outputPath} (${rs.length} bytes)\n`);
process.stdout.write(
  `SHAPE: nr_pubinputs=${vk.nrPubinputs} vk_ic.length=${vk.vkIc.length} ` +
    `alpha_g1.len=${vk.vkAlphaG1.length} beta_g2.len=${vk.vkBetaG2.length} ` +
    `gamme_g2.len=${vk.vkGammeG2.length} delta_g2.len=${vk.vkDeltaG2.length}\n`
);
