#!/usr/bin/env ts-node
//
// WITHDRAW_SOL_V1 witness dry run
//
// Compiles the circuit to /tmp, builds a deterministic dummy input using the
// existing witness helpers, runs generate_witness.js, and checks the witness
// against the R1CS with snarkjs wtns check.
//
// This script stops at snarkjs wtns check. It does NOT run:
//   - snarkjs powersoftau
//   - snarkjs groth16 setup
//   - snarkjs zkey / snarkjs zkey contribute / snarkjs zkey export verificationkey
//   - snarkjs groth16 prove
//   - snarkjs wtns export json
//
// No generated artifact (.r1cs, .wasm, .sym, .wtns, input.json, snapshot.json)
// is written into the repo. Everything stays under /tmp.
//
// SECURITY NOTES:
//   - TEST_SECRET is deterministic test data only. It is not a real user secret.
//   - The generated input.json contains TEST_SECRET as a decimal string.
//     It must not be committed. It lives under /tmp only.
//   - witness.wtns is private witness data. It must not be committed.
//     It lives under /tmp only.
//   - No proof, VK, zkey, or ptau is generated by this script.
//
// Usage:
//   npm run zk:witness-dry-run
//   npm run zk:witness-dry-run -- --keep-tmp
//   npm run zk:witness-dry-run -- --skip-npm-install
//   npm run zk:witness-dry-run -- --require-clean

import * as fs from "fs";
import * as path from "path";
import { spawnSync } from "child_process";

import { initPoseidon } from "../lib/zk_indexer/poseidon";
import {
  computeNoteCommitment,
  buildWitnessFromSnapshot,
  buildWithdrawSolV1CircomInputJson,
} from "../lib/zk_prover/witness";
import { buildSnapshot } from "../lib/zk_indexer/persistence";
import { normalizeNoteDepositedEvent } from "../lib/zk_indexer/event_log";

// ── Constants ─────────────────────────────────────────────────────────────────

// Deterministic dummy test values — same constants as tests/zk_prover_witness.ts.
// TEST_SECRET is NOT a real user secret. It exists only for circuit smoke testing.
const TEST_SECRET = 12345n;
const TEST_DENOMINATION = 1_000_000_000n;
const TEST_FEE = 10_000_000n;
const TEST_CHAIN_ID = 1n;
const TEST_EXPIRY_SLOT = 500_000n;
const DEPOSITOR = "7GhrwRsxkBrE1bKYdbBUbDZXhY4aBB8bG4d6V1BPAcXe";
const TEST_PROGRAM_ID = "E593efjkVU3Z6pJQtSLf7jECFeGBVy2UQZwET4nqLhyq";
const TEST_POOL_PDA = "HcAkT4obzEEaHyevyVvmU7drEtSUg1m4XxF1VTWGoCdm";
const TEST_CONFIG_PDA = "6DUXKzex1nLyFSvAfRRneaukfH1YXrQQ6t58vcYZpHJu";
const TEST_RECIPIENT = "FTu67mwyPuoaRB7U3zewHfAmRXvHC7y7zEt5a5eEwx8o";
const TEST_RELAYER = "7GhrwRsxkBrE1bKYdbBUbDZXhY4aBB8bG4d6V1BPAcXe";

// Locked parity vector: expected tx_hash for the above constants.
// This value is also pinned in tests/zk_prover_witness.ts and the Rust unit tests.
const LOCKED_TX_HASH_HEX =
  "17115e272898a4cca8177791e2e99f51b2e01e7bc2d1381164217f6ef931bcac";

const BASE_PARAMS = {
  programId: TEST_PROGRAM_ID,
  poolPda: TEST_POOL_PDA,
  configPda: TEST_CONFIG_PDA,
  recipient: TEST_RECIPIENT,
  relayer: TEST_RELAYER,
  denomination: TEST_DENOMINATION,
  fee: TEST_FEE,
  chainId: TEST_CHAIN_ID,
  expirySlot: TEST_EXPIRY_SLOT,
};

const CIRCOM_ACCOUNTS = {
  programId: TEST_PROGRAM_ID,
  poolPda: TEST_POOL_PDA,
  configPda: TEST_CONFIG_PDA,
  recipient: TEST_RECIPIENT,
  relayer: TEST_RELAYER,
};

// ── Paths ─────────────────────────────────────────────────────────────────────

const PROJECT_ROOT = path.resolve(__dirname, "..");
const CIRCUIT_SRC = path.join(
  PROJECT_ROOT,
  "circuits",
  "WITHDRAW_SOL_V1.circom"
);

const TMP_TOOLCHAIN = "/tmp/withdraw_sol_v1_toolchain";
const TMP_DRY_RUN = "/tmp/withdraw_sol_v1_witness_dry_run";
const TMP_BUILD = path.join(TMP_DRY_RUN, "build");
const TMP_INPUT = path.join(TMP_DRY_RUN, "input");
const TMP_WITNESS = path.join(TMP_DRY_RUN, "witness");

const PATHS = {
  r1cs: path.join(TMP_BUILD, "WITHDRAW_SOL_V1.r1cs"),
  wasm: path.join(TMP_BUILD, "WITHDRAW_SOL_V1_js", "WITHDRAW_SOL_V1.wasm"),
  generateWitness: path.join(
    TMP_BUILD,
    "WITHDRAW_SOL_V1_js",
    "generate_witness.js"
  ),
  snarkjsCli: path.join(TMP_TOOLCHAIN, "node_modules", "snarkjs", "cli.js"),
  circomlibPkg: path.join(
    TMP_TOOLCHAIN,
    "node_modules",
    "circomlib",
    "package.json"
  ),
  snarkjsPkg: path.join(
    TMP_TOOLCHAIN,
    "node_modules",
    "snarkjs",
    "package.json"
  ),
  snapshot: path.join(TMP_INPUT, "snapshot.json"),
  input: path.join(TMP_INPUT, "input.json"),
  metadata: path.join(TMP_INPUT, "metadata.json"),
  witness: path.join(TMP_WITNESS, "witness.wtns"),
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function log(msg: string): void {
  console.log(msg);
}

function run(
  cmd: string,
  args: string[],
  options: { cwd?: string; capture?: boolean } = {}
): string {
  const result = spawnSync(cmd, args, {
    cwd: options.cwd ?? PROJECT_ROOT,
    encoding: "utf-8",
    stdio: options.capture ? "pipe" : "inherit",
  });
  if (result.error) {
    throw new Error(`${cmd}: ${result.error.message}`);
  }
  if (result.status !== 0) {
    const detail = options.capture ? result.stderr ?? "" : "";
    throw new Error(
      `${cmd} ${args.join(" ")} exited with status ${result.status}${
        detail ? "\n" + detail : ""
      }`
    );
  }
  return options.capture ? result.stdout ?? "" : "";
}

function ensureDir(p: string): void {
  fs.mkdirSync(p, { recursive: true });
}

function rmrf(p: string): void {
  fs.rmSync(p, { recursive: true, force: true });
}

function requireFile(p: string, label: string): void {
  if (!fs.existsSync(p)) {
    throw new Error(`Required file not found: ${label} (${p})`);
  }
}

function writeJson(p: string, obj: unknown): void {
  fs.writeFileSync(p, JSON.stringify(obj, null, 2), "utf-8");
}

function readJsonVersion(pkgPath: string): string {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as {
    version: string;
  };
  return pkg.version;
}

function assertEqual<T>(actual: T, expected: T, label: string): void {
  if (actual !== expected) {
    throw new Error(
      `Assertion failed [${label}]:\n  expected: ${JSON.stringify(
        expected
      )}\n  actual:   ${JSON.stringify(actual)}`
    );
  }
}

function assertRepoClean(): void {
  const status = run("git", ["status", "--short"], { capture: true }).trim();
  if (status.length > 0) {
    throw new Error(`Repo working tree is not clean:\n${status}`);
  }
}

function assertNoRepoArtifacts(): void {
  const result = spawnSync(
    "find",
    [
      ".",
      "(",
      "-name",
      "*.r1cs",
      "-o",
      "-name",
      "*.zkey",
      "-o",
      "-name",
      "*.ptau",
      "-o",
      "-name",
      "*.wasm",
      "-o",
      "-name",
      "*.sym",
      "-o",
      "-name",
      "*.wtns",
      "-o",
      "-name",
      "proof.json",
      "-o",
      "-name",
      "verification_key.json",
      "-o",
      "-name",
      "public.json",
      "-o",
      "-name",
      "witness.json",
      "-o",
      "-name",
      "input.json",
      "-o",
      "-name",
      "snapshot.json",
      ")",
      "-not",
      "-path",
      "./node_modules/*",
      "-not",
      "-path",
      "./target/*",
      "-not",
      "-path",
      "./.git/*",
      "-print",
    ],
    {
      cwd: PROJECT_ROOT,
      encoding: "utf-8",
      stdio: "pipe",
    }
  );
  const found = (result.stdout ?? "").trim();
  if (found.length > 0) {
    throw new Error(`Generated artifacts found in repo:\n${found}`);
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const keepTmp = argv.includes("--keep-tmp");
  const skipNpmInstall = argv.includes("--skip-npm-install");
  const requireClean = argv.includes("--require-clean");

  log("=== WITHDRAW_SOL_V1 witness dry run ===");
  log("");

  // 1. Verify project root
  if (!fs.existsSync(CIRCUIT_SRC)) {
    throw new Error(
      `Circuit source not found: ${CIRCUIT_SRC}\nRun this script from the project root.`
    );
  }
  log(`[1/9] Project root: ${PROJECT_ROOT}`);

  // 2. Check circom toolchain
  const circomVersionRaw = run("circom", ["--version"], { capture: true });
  if (!circomVersionRaw.includes("2.1.6")) {
    throw new Error(`circom 2.1.6 required, got: ${circomVersionRaw.trim()}`);
  }
  log(`[2/9] circom: ${circomVersionRaw.trim()}`);

  // 3. Prepare /tmp directories
  if (!keepTmp) {
    log("[3/9] Preparing /tmp directories (use --keep-tmp to reuse)");
    rmrf(TMP_TOOLCHAIN);
    rmrf(TMP_DRY_RUN);
  } else {
    log("[3/9] --keep-tmp: reusing existing /tmp directories");
  }
  ensureDir(TMP_TOOLCHAIN);
  ensureDir(TMP_BUILD);
  ensureDir(TMP_INPUT);
  ensureDir(TMP_WITNESS);

  // 4. Install temporary npm packages under /tmp only
  if (skipNpmInstall) {
    log("[4/9] --skip-npm-install: verifying packages under /tmp");
    requireFile(PATHS.circomlibPkg, "circomlib package.json");
    requireFile(PATHS.snarkjsPkg, "snarkjs package.json");
    const circomlibVersion = readJsonVersion(PATHS.circomlibPkg);
    const snarkjsVersion = readJsonVersion(PATHS.snarkjsPkg);
    assertEqual(circomlibVersion, "2.0.5", "circomlib version");
    assertEqual(snarkjsVersion, "0.7.4", "snarkjs version");
    log(`    circomlib@${circomlibVersion} ✓`);
    log(`    snarkjs@${snarkjsVersion} ✓`);
  } else {
    log("[4/9] Installing circomlib@2.0.5 and snarkjs@0.7.4 under /tmp");
    // Run npm in /tmp, not in the repo — no changes to repo node_modules or package.json.
    run("npm", ["init", "-y"], { cwd: TMP_TOOLCHAIN, capture: true });
    run("npm", ["install", "--no-save", "circomlib@2.0.5", "snarkjs@0.7.4"], {
      cwd: TMP_TOOLCHAIN,
    });
    requireFile(PATHS.snarkjsCli, "snarkjs cli.js");
    log("    circomlib@2.0.5 and snarkjs@0.7.4 installed");
  }

  // Pre-compile: refuse to run if repo already contains generated artifacts.
  // We do not enforce a clean working tree here because this script may itself
  // be an uncommitted file during development. Use --require-clean to opt in.
  log("[pre] Checking for stray artifacts in repo");
  assertNoRepoArtifacts();
  log("    no artifacts");

  if (requireClean) {
    log("[pre] --require-clean: asserting clean working tree");
    assertRepoClean();
    log("    working tree clean");
  }

  // 5. Compile circuit to /tmp only — no artifacts written to repo
  log("[5/9] Compiling WITHDRAW_SOL_V1.circom → /tmp");
  run("circom", [
    CIRCUIT_SRC,
    "--r1cs",
    "--wasm",
    "--sym",
    "-l",
    path.join(TMP_TOOLCHAIN, "node_modules"),
    "-o",
    TMP_BUILD,
  ]);
  requireFile(PATHS.r1cs, "WITHDRAW_SOL_V1.r1cs");
  requireFile(PATHS.wasm, "WITHDRAW_SOL_V1.wasm");
  requireFile(PATHS.generateWitness, "generate_witness.js");
  log("    .r1cs, .wasm, generate_witness.js written to /tmp");

  // 6. R1CS info
  log("[6/9] R1CS info:");
  run("node", [PATHS.snarkjsCli, "r1cs", "info", PATHS.r1cs]);

  // 7. Build dummy input JSON — all files written to /tmp only
  log("[7/9] Building dummy input JSON");
  await initPoseidon();

  const commitment = computeNoteCommitment(TEST_SECRET, TEST_DENOMINATION);
  const event0 = normalizeNoteDepositedEvent({
    commitment,
    denomination: TEST_DENOMINATION.toString(),
    leaf_index: 0,
    depositor: DEPOSITOR,
    slot: "300",
  });

  writeJson(PATHS.snapshot, buildSnapshot([event0]));

  const { witness } = buildWitnessFromSnapshot(
    PATHS.snapshot,
    { leafIndex: 0 },
    TEST_SECRET,
    BASE_PARAMS
  );

  // input.json contains TEST_SECRET as a decimal string — must not be committed.
  const circomInput = buildWithdrawSolV1CircomInputJson(
    witness,
    TEST_SECRET,
    CIRCOM_ACCOUNTS
  );
  writeJson(PATHS.input, circomInput);

  const txHashHex = BigInt(circomInput.tx_hash).toString(16).padStart(64, "0");
  const rootHex = BigInt(circomInput.root).toString(16).padStart(64, "0");
  const nullifierHashHex = BigInt(circomInput.nullifier_hash)
    .toString(16)
    .padStart(64, "0");

  const metadata = {
    inputPath: PATHS.input,
    signalKeyCount: Object.keys(circomInput).length,
    pathElementsLength: circomInput.path_elements.length,
    pathIndicesLength: circomInput.path_indices.length,
    txHashHex,
    rootHex,
    nullifierHashHex,
    circuitVersion: circomInput.circuit_version,
    note: "dummy test input only — do not commit",
  };
  writeJson(PATHS.metadata, metadata);

  // Verify expected values against locked constants
  assertEqual(metadata.signalKeyCount, 21, "signalKeyCount");
  assertEqual(metadata.pathElementsLength, 20, "pathElementsLength");
  assertEqual(metadata.pathIndicesLength, 20, "pathIndicesLength");
  assertEqual(metadata.txHashHex, LOCKED_TX_HASH_HEX, "txHashHex");
  assertEqual(metadata.circuitVersion, "1", "circuitVersion");

  log(`    signalKeyCount:       ${metadata.signalKeyCount}`);
  log(`    pathElementsLength:   ${metadata.pathElementsLength}`);
  log(`    pathIndicesLength:    ${metadata.pathIndicesLength}`);
  log(`    txHashHex:            ${metadata.txHashHex}`);
  log(`    rootHex:              ${metadata.rootHex}`);
  log(`    nullifierHashHex:     ${metadata.nullifierHashHex}`);
  log(`    circuitVersion:       ${metadata.circuitVersion}`);
  log(`    inputPath:            ${metadata.inputPath}`);
  log(`    metadataPath:         ${PATHS.metadata}`);
  log("    all expected values confirmed");

  // 8. Generate witness — output stays in /tmp, never enters repo
  log("[8/9] Generating witness");
  run("node", [PATHS.generateWitness, PATHS.wasm, PATHS.input, PATHS.witness]);

  requireFile(PATHS.witness, "witness.wtns");
  const witnessSize = fs.statSync(PATHS.witness).size;
  log(
    `    witness.wtns: ${PATHS.witness} (${Math.round(witnessSize / 1024)} KB)`
  );

  // 9. Witness constraint check — confirms the dummy input satisfies all 6552 constraints
  log("[9/9] Checking witness against R1CS");
  run("node", [PATHS.snarkjsCli, "wtns", "check", PATHS.r1cs, PATHS.witness]);

  // Post-run: confirm no generated artifacts leaked into repo
  log("");
  log("=== Repo safety checks ===");
  assertNoRepoArtifacts();
  log("no generated artifacts in repo");

  const gitStatus = run("git", ["status", "--short"], { capture: true }).trim();
  if (gitStatus.length > 0) {
    log(`git status:\n${gitStatus}`);
  } else {
    log("git status: clean");
  }

  log("");
  log("WITNESS_DRY_RUN_PASS");
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err);
  console.error("\n[FAIL]", msg);
  process.exit(1);
});
